version: "3.6"

services:

  web:
    image: nginx:1.19
    depends_on: 
      - app
    ports:
      - 8080:80
    volumes:
      - ./.deploy/nginx/conf:/etc/nginx/conf.d
      - ./public:/usr/share/nginx/html

  app:
    build: ./.deploy/php
    volumes:
      - ./application:/source/application/
      - ./public:/source/public/
      - ./system:/source/system/

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./.deploy/mysql/data:/var/lib/mysql
